version: '3'
services:
  php:
    image: noriakioshita/timesheet_frontend_r:latest
    ports:
      - 8080:8080
    restart: always
    volumes: 
      - parameter_share:/parameter/share

  tabu:
    image: noriakioshita/timesheet_backend
    ports:
      - 5000:5000
    restart: always
    volumes: 
      - parameter_share:/parameter/share
volumes: 
  parameter_share: