apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: php
    spec:
      containers:
        - image: noriakioshita/timesheet_frontend_r:latest
          name: php
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /parameter/share
              name: parameter-share
      restartPolicy: Always
      volumes:
        - name: parameter-share
          persistentVolumeClaim:
            claimName: parameter-share
status: {}
